### PR TITLE
[Examples] Deribit examples

### PR DESCRIPTION
**Pull request by jakubkalicki**
Added examples for Deribit exchange

### CODE REVIEW

**Comment by jakubkalicki** [comment]
This needs to wait until Deribit module lands in nexus repo.

**Comment by timmolter** [comment]
According to Travis CI, there's a compile error in your Deribit example code.

**Comment by walec51** [comment]
@jakubkalicki will you be working on this PR?
if not then will have to close it

**Comment by jakubkalicki** [comment]
@walec51 Issues have been fixed

**Pull request merged**
