### PR TITLE
[general] Change the scope of lombok to provided

### PR DESCRIPTION
**Pull request by bigscoop**
Lombok dependency is needed only at runtime, not at compile-time, so it has to be used with scope `provided`

see https://projectlombok.org/setup/maven

### CODE REVIEW

**Comment by bigscoop** [comment]
ping @timmolter @makarid

**Comment by walec51** [comment]
@bigscoop it we use it only at compile time I think it would be safe to just add it to the root pom.xml in

  
  <dependencies>

instead of the pom.xml of each module

as modules that do not use it will stay unaffected anyway

**Comment by bigscoop** [comment]
@walec51 good idea! moved the dependency to parent pom only

also fixed wrong version of parent in xchange-stream-kucoin-module

**Comment by bigscoop** [comment]
ping @walec51 @timmolter @makarid

**Comment by bigscoop** [comment]
ping @walec51 @timmolter @makarid

**Pull request merged**
