### PR TITLE
Binance streaming exchange: NPE if disconnect() method is called twice

### PR DESCRIPTION
**Pull request by eschava**

### CODE REVIEW

**Comment by eschava** [comment]
How to restart the checks? I'm sure that failure is not related to my changes

**Comment by timmolter** [comment]
OK, I kicked off a new run...

**Comment by earce** [comment]
seems strange this is failing

**Comment by eschava** [comment]
please, restart the checks. I guess that everything should be OK now

**Comment by timmolter** [comment]
github won't let me restart it and I don't know why. Maybe the PR is now too old??

**Comment by eschava** [comment]
please rerun the checks

**Comment by timmolter** [comment]
I wish I could. Github shows no button for restarting. Can you maybe push some trivial change and see if it triggers it?

**Pull request merged**
