### PR TITLE
[coingi] added demo examples

### PR DESCRIPTION
**Pull request by jmcklondonuk**
Hey, I've added examples for https://coingi.com
They show how to:
* buy / sell BTC for EUR
* check what's in your wallet (balances)
* fetch your open orders
* find an order by Order ID
* fetch the public OrderBook (i.e. what's available for sale / to buy right now on Coingi)
* fetch the last trades (i.e. what was just traded by Coingi users)

### CODE REVIEW

**Comment by jmcklondonuk** [comment]
Please advise. xchange-coingi is unresolvable, although yesterday xchange-coingi has been merged.
[ERROR] Failed to execute goal on project xchange-examples: Could not resolve dependencies for project org.knowm.xchange:xchange-examples:jar:4.3.8-SNAPSHOT: Could not find artifact org.knowm.xchange:xchange-coingi:jar:4.3.8-SNAPSHOT in sonatype-oss-public (https://oss.sonatype.org/content/groups/public/) -> [Help 1]

**Comment by timmolter** [comment]
try going to your `.mvn` repository on your file system and deleting the `xchange-coingi`. Are you using Eclipse by chance?

**Comment by jmcklondonuk** [comment]
@timmolter Hey Tim, that's a misunderstanding. It works locally. Of course, first it requires "mvn install" of the xchange-coingi module. In Travis CI, the build fails because Travis cannot resolve xchange-coingi. Since xchange-coingi has been merged very recently (yesterday) into develop, do we perhaps need more time for the snapshot to be available?

**Comment by timmolter** [comment]
Try adding `<module>xchange-coingi</module>` to parent `pom.xml`.

**Pull request merged**
