### PR TITLE
[krakenfutures] Adding Kraken futures support

### PR DESCRIPTION
**Pull request by makarid**

### CODE REVIEW

**Comment by timmolter** [comment]
is kraken-futures a replacement to crypto-facilities? Same API, just a rename?

**Comment by makarid** [comment]
> is kraken-futures a replacement to crypto-facilities? Same API, just a rename?

Yes, but i have added more endpoints. Cryptofacilities has been bought by Kraken so cryptofacilities doesn't exists anymore.

**Comment by makarid** [comment]
Right now this implementation has an issue on kraken-futures-stream websocket authentication endpoints. If the stream gets disconnection or something happens and the connection restarts, it doesn't re-authenticate itself. I need to fix it

**Comment by makarid** [comment]
I finally fixed the issue

**Pull request merged**
