### PR TITLE
Add cumulative amount on FTX Order Subscription. Fixes #4477

### LINKED ISSUE #4477: Missing cumulative amount on FTX Order Subscription

### PR DESCRIPTION
**Pull request by peyerroger**

### CODE REVIEW

**Comment by peyerroger** [comment]
@timmolter If you'd be so kind again? It's a one liner. Thanks very much!

**Comment by aasche** [comment]
would be great to have this in!

**Comment by peyerroger** [comment]
@timmolter Any chance you or anyone from your team could take a look at this soon?

**Comment by peyerroger** [comment]
Thanks a lot!

**Pull request merged**
