### PR TITLE
[ftx] remove broken order book checksum

### LINKED ISSUE #4014: Stream FTX : Checksum is not correct!
Hi,

I try the stream with FTX (code is like the example) and this part cause an issue : Checksum is not correct!

class FtxStreamingAdapters

                if (!calculatedChecksum.equals(message.getChecksum())) {
                  throw new RuntimeException("Checksum is not correct!");
                }
If i comment this lines (88/89/90), it's worked. I receive the orderbook.

### PR DESCRIPTION
**Pull request by phraktle**
Checksumming the FTX order book is currently broken. Fixing it would require storing the original values verbatim to retain number formatting. It's also very wasteful to do this on every change, so I suggest removing this completely. Fixes  #4014.

### CODE REVIEW

**Comment by bitcoinmat-dev** [comment]
Ok, but how will we know that the orderbook is correct? Thanks

**Comment by phraktle** [comment]
> Ok, but how will we know that the orderbook is correct? Thanks

how do you know in any of the other XChange streaming client implementations? :)

if you feel like taking a crack at a correct implementation (which is also optional for performance reasons), i'm in favor. in the meantime, the implementation removed by this PR is fundamentally flawed and stops streaming from working at all.

**Comment by earce** [comment]
@phraktle can you make get orderbook checksum just extract the current checksum that is part of the message, then when you try to compare it, it will pass, and add a TODO on the method describing what needs to be done so it's understood as something to potentially implement later

**Comment by phraktle** [comment]
@earce I wouldn’t consider this a “to do” item.

**Comment by earce** [comment]
I would disagree https://docs.ftx.com/#orderbooks, ensuring your client is in sync with server should be part of implementation if the exchange has it.

**Comment by earce** [comment]
I will not approve this without a TODO, you will have to find someone else to merge it.

**Comment by mdvx** [comment]
can we merge this in?

**Comment by mdvx** [comment]
https://github.com/knowm/XChange/pull/4151/commits/20154ce6504cd077d219888deb1f8e5e7737f254

**Comment by makarid** [comment]
Hello, please do not merge this. Right now the checksum is working without any issue.

**Pull request closed without merging**
