### PR TITLE
[core] Introduce junit5

### PR DESCRIPTION
**Pull request by bigscoop**
- Added dependency to `junit-vintage-engine` to enable junit 5 runner, but leaving existing junit 4 tests available and untouched
- Changed project code level to java 11

### CODE REVIEW

**Comment by timmolter** [comment]
for compatibility with Android, we need to leave it on Java 8

**Comment by bigscoop** [comment]
but the project can't be built with java 8 anymore

**Comment by iromu** [comment]
> for compatibility with Android, we need to leave it on Java 8

Android supports 11 and 17

**Comment by bigscoop** [comment]
ping @timmolter @walec51 @makarid

**Comment by walec51** [comment]
Android does not support full Java 11. Android is Java 8 plus features backported from newer versions.

To bring back Android support we should add a CI Job that build a small example app that is build using Android SDK an that imports this library. 

Any one up for this task?

**Comment by bigscoop** [comment]
Rolled back the code level changes. Now it is only junit 5

**Pull request merged**
