### PR TITLE
[gatecoin] Fixed placement of orders

### LINKED ISSUE #2417: Request could not be deserialized. (HTTP status code: 200) (Gatecoin)
Exception in thread "Thread-7" org.knowm.xchange.gatecoin.dto.GatecoinException: Request could not be deserialized. (HTTP status code: 200)

anyone getting this error when try to trade with the gatecoin api? was working fine a few months ago?

i used the code from the example, tried both raw and generic both seem to give off the same error...

### PR DESCRIPTION
**Pull request by 199sm**
Fixed #2417

### CODE REVIEW

**Comment by npomfret** [comment]
I'm using the gatecoin implementation without this fix and it's working fine.  What change does this make?

**Comment by npomfret** [comment]
This used to work I think - so has the gatecoin API changed?  And if  so, do we know if it's isolated to this one method?

**Comment by 199sm** [comment]
I had the [same issue](https://www.facebook.com/Gatecoin/posts/1661592983932661?comment_id=1661712407254052) and these changes fixed it. Maybe need the same fix for withdrawals, but I'm not sure and can't check it.

**Comment by makarid** [comment]
Hello, i am still get the "deserialized" error only when i am running my app from cmd.When i run the same code from intellij i don't get this error.Does anyone still has the deserialized issue?Thanks

**Pull request merged**
