### PR TITLE
Binance + CoinbasePro meta data all loaded via API

### PR DESCRIPTION
**Pull request by amjad1210**
We shouldn't use hard coded values but rather load them from the API if they're available.

All metadata for CoinbasePro + Binance is loaded via the API now.
This includes base amount scale, counter amount scale, wallet amount scale and withdrawal fees.

Added baseScale field which is the amount precision for a BID order type.

### CODE REVIEW

**Comment by amjad1210** [comment]
FYI

CurrencyPairMetaData:
  - baseScale is the precision amount for the base currency.
  - priceScale is the precision amount for the counter currency.

**Comment by timmolter** [comment]
could you please fix the conflicting files?

**Comment by amjad1210** [comment]
I've fixed the conflicts.

**Comment by walec51** [comment]
you now get a NPE when you try to use Binances Public API without passing any credentials because of this PR ....

**Comment by cymp** [comment]
Yes I can confirm...

**Comment by walec51** [comment]
quick fix: https://github.com/knowm/XChange/pull/3099
however this whole change should be rethinked

**Comment by amjad1210** [comment]
Sorry I've always used it with credentials completely slipped my mind that people may be using it without credentials. I'll add a fix within the next few hours please bare with me.

**Comment by amjad1210** [comment]
Fix in #3100

**Pull request merged**
