### PR TITLE
[CoinbasePro] Fix trade constructor

### LINKED ISSUE #3007: [Coinbase Pro] Issue on getTrades method
stack_trace: si.mazi.rescu.HttpStatusIOException: Conflicting property-based creators: already had implicitly discovered creator [constructor for org.knowm.xchange.coinbasepro.dto.marketdata.CoinbaseProTrade, annotations: [null]], encountered another: [constructor for org.knowm.xchange.coinbasepro.dto.marketdata.CoinbaseProTrade, annotations: [null]]
 at [Source: (String)"[{"time":"2019-03-18T17:26:33.242Z","trade_id":18311691,"price":"3506.43000000","size":"0.13541072","side":"buy"},{"time":"2019-03-18T17:26:33.242Z","trade_id":18311690,"price":"3506.45000000","size":"0.00100000","side":"buy"},{"time":"2019-03-18T17:26:29.436Z","trade_id":18311689,"price":"3506.46000000","size":"0.03030000","side":"sell"},{"time":"2019-03-18T17:26:28.778Z","trade_id":18311688,"price":"3506.48000000","size":"0.01805692","side":"buy"},{"time":"2019-03-18T17:26:24.186Z","trade_id":"[truncated 10852 chars]; line: 1, column: 1]
        at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
        at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:175)
        at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:163)
        at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119)
        at com.sun.proxy.$Proxy247.getTrades(Unknown Source)
        at org.knowm.xchange.coinbasepro.service.CoinbaseProMarketDataServiceRaw.getCoinbaseProTrades(CoinbaseProMarketDataServiceRaw.java:93)

### PR DESCRIPTION
**Pull request by trixprod**
Please before merging, consider :
- What was the original purpose of two constructors ?
- Does the Xchange framework allow null JsonProperty ?
Fixes #3007

### CODE REVIEW

**Comment by makarid** [comment]
@trixprod bette delete the other constructor, the one that has market_order_id. JsonProperty doesn't allowed null.

**Comment by trixprod** [comment]
As you wish. I let you make the pull request and i will delete mine so.

**Comment by makarid** [comment]
ok

**Comment by makarid** [comment]
You can close the PR

**Pull request closed without merging**
