### PR TITLE
More informative exceptions

### PR DESCRIPTION
**Pull request by walec51**
For now the first commit showing the direction I want to take.

Adding a *ErrorAdapter to every module which tries to throw more informative ExchangeException child class if it recognizes a common error situation like: passing a not supported currency pair or failing to authenticate.

The CryptopiaErrorAdapter depends on the  CryptopiaBaseResponse. Other exchanges with more HTTP compliant APIs will require passing the HTTP status and error response object to an error adapter.

### CODE REVIEW

**Comment by walec51** [comment]
expanded concept to Poloniex and started attacking #2533

please give me some feedback if this is going in the right direction

**Comment by timmolter** [comment]
Looks goo except that you should put the error handling method in the BaseService, rather than in the adapter. See `GDAXBaseService`.

**Comment by walec51** [comment]
This will make it harder to test:

```
/** @author walec51 */
public class CryptopiaBaseServiceTest {

  private Exchange exchange;
  private CryptopiaBaseService service;

  @Before
  public void setUp() {
    exchange = mock(Exchange.class);
    // ... exchange specification mocking ...
    service = new CryptopiaBaseService(exchange);
  }

  @Test(expected = CurrencyPairNotValidException.class)
  public void throwIfErrorResponse_wrongMarket() {
    // Cryptopia actualy sets successful = true in this situation
    CryptopiaBaseResponse response =
        new CryptopiaBaseResponse(true, null, null, "Market STRG_BTC not found");
    service.throwIfErrorResponse(response);
  }

  @Test(expected = ExchangeException.class)
  public void throwIfErrorResponse_unrecognizedErrorMessage() {
    CryptopiaBaseResponse response =
        new CryptopiaBaseResponse(false, null, null, "Some other error message");
    service.throwIfErrorResponse(response);
  }

  @Test(expected = ExchangeException.class)
  public void throwIfErrorResponse_unsuccessfulWithoutErrorMessage() {
    CryptopiaBaseResponse response = new CryptopiaBaseResponse(false, null, null, null);
    service.throwIfErrorResponse(response);
  }

  @Test
  public void throwIfErrorResponse_successfulWithoutErrorMessage() {
    CryptopiaBaseResponse response = new CryptopiaBaseResponse(true, null, null, null);
    service.throwIfErrorResponse(response);
  }
}
```

as I have to add a lot of mocking just to test error handling.

Do we really want this?
Do many other modules implement error handling like GDAXs one does ?

**Comment by walec51** [comment]
@timmolter please decide if you agree with my argumentation or should I just stick with the *BaseService.handleError method pattern as shown in GDAX

**Comment by walec51** [comment]
I've pushed the refactored code and also made exception / DTO handling more consistent in the two modules. Please take a look.

My approach contradicts one rule from from step 7 of https://github.com/knowm/XChange/wiki/New-Implementation-Best-Practices

> Also catch all exchange-specific Exceptions in the *Raw class and re-throw them as ExchangeExceptions

To me exchange specific exceptions are just a specific case of DTO and therefore I see the above rule internally inconsistent with another rule in the same paragraph:

> The *Raw class should fetch the JSON and deserialize it into exchange-specific DTOs.

If *Raw classes should stick to the Exchanges representation of data then I think this should also apply to exceptions / error data. In one case (like in this PR) the exchanges API will return an error message but in another it can return an error code which may have to be mapped to a message and some context data. I assume that we have *Raw classes for rare cases when XChanges generic data model is too generic and one has to call those *Raw methods directly to get access to exchange-specific fields. I think that's a good approach and throwing exchange specific exceptions would be an extension of it.

**Comment by timmolter** [comment]
looks good

**Comment by walec51** [comment]
thank you, I modified step 7 in https://github.com/knowm/XChange/wiki/New-Implementation-Best-Practices in accordance to this change and I'm proceeding with enhancing error handling in more modules

**Pull request merged**
