### PR TITLE
[CoinMarketCap] Implement new api

### PR DESCRIPTION
**Pull request by jakubkalicki**
#2900

Work in progress

### CODE REVIEW

**Comment by johnzweng** [comment]
@jakubkalicki Thank you for working on this! 😃👍 

But I am stupid. I don't know how I couldn't see this PR and started working on this myself. 🤦‍♂️ 

Nevertheless.. if you can use anything from it, feel free to look at:
https://github.com/johnzweng/XChange/commit/c7d82ecb98d111335241a19251a0c5deee4a252b 🙂

**Comment by jakubkalicki** [comment]
@johnzweng 

Sure, mate, i will extract what i can from your commit ;)

**Comment by jakubkalicki** [comment]
@timmolter, @johnzweng 

Ok, guys, you can review my code, if you would like. I have implemented these endpoints: 
https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyInfo
https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyMap
https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyListingsLatest
https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyQuotesLatest

**Comment by johnzweng** [comment]
Thank you @jakubkalicki 
In general looks good to me. Thanks again! 👍 

One minor issue: the formatting looks different from what the `fmt-maven-plugin` Plugin produces. 
If I run `mvn --projects "xchange-coinmarketcap" clean compile` from the project root directory I see a lot of changed files (because the `fmt-maven-plugin` changes the formatting of most *.java files).
Maybe you could check in the files again after being processed by the maven formatting plugin?

Otherwise it's fine for me. 🙂

**Comment by johnzweng** [comment]
Thank you! 🙂 Looks good to me, but let's wait for @timmolter what he says.

**Comment by DjihadBengati** [comment]
Good work ! thank you !

**Comment by johnzweng** [comment]
Short update on this: I realised that the exchange doesn't use the API key when used in my own project. I described and fixed the problem in #2952 PR.

**Pull request merged**
