### PR TITLE
Kraken: add support for OHLC Streaming

### PR DESCRIPTION
**Pull request by rvullriede**
This PR adds support for OHLC Streaming for Kraken. It requires a (backward-compatible) change to NettyStreamingService in order to allow streaming of OHLC for multiple intervals for the same currrency pair.
Without this change the channelId won't be unique and interfere with each other.

### CODE REVIEW

**Comment by timmolter** [comment]
If you fix the conflicts, I will merge this.

**Comment by rvullriede** [comment]
Rebased and fixed conflicts.

**Comment by timmolter** [comment]
Hello @rvullriede After merging, `import info.bitrich.xchangestream.kraken.dto.KrakenStreamingOhlc` seems to be missing. Would you kindly take a look?

**Comment by timmolter** [comment]
ok, thanks. Can you make a new PR?

**Pull request merged**
