### PR TITLE
[binance] Add tickers

### PR DESCRIPTION
**Pull request by bigscoop**
- Added mapping symbol -> currency pair (got from exchange info)
- Moved exchangeInfo-methods to MarketDataService
- Updated integration tests
- Added requests for idea http client
- Simplified dto's

### CODE REVIEW

**Comment by rizer1980** [comment]
Hi.
Two requests for tickers:
api/v3/ticker/price - **Latest price** for a symbol or symbols.
api/v3/ticker/bookTicker - **Best price/qty** on the order book for a symbol or symbols.
But there is no volume and quoteVolume and ticker time is only last moment.

If I understand correctly, we should get a 24 hour ticker.
this api is fit:
https://binance-docs.github.io/apidocs/spot/en/#24hr-ticker-price-change-statistics

**Comment by bigscoop** [comment]
> Hi. Two requests for tickers: api/v3/ticker/price - **Latest price** for a symbol or symbols. api/v3/ticker/bookTicker - **Best price/qty** on the order book for a symbol or symbols. But there is no volume and quoteVolume and ticker time is only last moment.
> 
> If I understand correctly, we should get a 24 hour ticker. this api is fit: https://binance-docs.github.io/apidocs/spot/en/#24hr-ticker-price-change-statistics

Hi. Yep, good idea :+1: 
will change the implementation

**Comment by rizer1980** [comment]
done 
#4868

**Comment by bigscoop** [comment]
@timmolter 

I propose to review and merge the https://github.com/knowm/XChange/pull/4868 first. Then I can integrate the changes to my branch

**Comment by timmolter** [comment]
merged 4868

**Comment by bigscoop** [comment]
> merged 4868

done, feel free to review

**Comment by bigscoop** [comment]
@timmolter ping

**Pull request merged**
