### PR TITLE
[Streaming] Adding proper handlers to subscription for reconnection

### PR DESCRIPTION
**Pull request by earce**
Upon re-connection a subscribe without a proper onError observer is used `EmptyCompletableObserver.java` which has an onError method

`public void onError(Throwable e) {
        this.lazySet(DisposableHelper.DISPOSED);
        RxJavaPlugins.onError(new OnErrorNotImplementedException(e));
    }`

this triggers noisy stack traces in the logs so I have modified to log graceful error messages and to add a proper onError handler.

### CODE REVIEW

**Comment by earce** [comment]
@badgerwithagun @mdvx hey do you guys think you could  opine on this when you have some time?

**Comment by earce** [comment]
Have also added the ability to subscribe to disconnects

**Comment by badgerwithagun** [comment]
This disconnect publusher only seems to emit due a temporary disconnection, not a permanent one. Why is this?  Wouldn't it make sense to emit in both cases?

**Comment by earce** [comment]
@badgerwithagun updated as per your comment

**Comment by earce** [comment]
Have also added some improved logging to `WebSocketClientHandler.java`

**Comment by earce** [comment]
@badgerwithagun hey wanted to bring this back up, want to make sure I get this in as part of this months cut :)

**Comment by badgerwithagun** [comment]
Apologies for the delay - I've been busy with some other things.

Approving this for now, but @mdvx - we were discussing some options for a stream of status updates (i.e. a single stream of messages containing statuses like `CONNECTED, DISCONNECTED, PARTIALLY_CONNECTED` etc).  That would be a better solution here. Are we any closer to a conclusion on that?

**Comment by earce** [comment]
thanks @badgerwithagun much appreciated, and just for my own understanding what you mean here is as opposed to having different methods to subscribe on you would subscribe on a single channel and get the state changes via that single channel?

**Pull request merged**
