### PR TITLE
change api-nonce to api-expires for bitmex restful api

### PR DESCRIPTION
**Pull request by declan94**
When running multiple programs, the original 'api-nonce' signature mode has significant problems.

This PR changes the signature mode for Bitmex to the new version, which specifies 'api-expires' instead of 'api-nonce'.

Here's the relative api document: [https://www.bitmex.com/app/apiKeysUsage](https://www.bitmex.com/app/apiKeysUsage)

### CODE REVIEW

**Comment by timmolter** [comment]
what is `lag` for?

**Comment by declan94** [comment]
@timmolter It means how long before the signature expires. The variable name may be confusing, do you have any suggestions?

**Comment by timmolter** [comment]
According to their docs: api-expires: A UNIX timestamp after which the request is no longer valid. This is to prevent replay attacks.

It's not even a nonce anymore, really. I'd change `CurrentTimeSecNonceFactory` to `ExpirationTimeFactory` and call `lag` something like `expirationTime` and comment it as being in seconds.

**Comment by declan94** [comment]
Have modified the code according to your suggestions.

**Pull request merged**
