### PR TITLE
[bl3p] Bl3p Exchange Support

### PR DESCRIPTION
**Pull request by AmazingDreams**
Website: https://bl3p.eu/

Api documentation: https://github.com/BitonicNL/bl3p-api/tree/master/docs

Let me know if anything is missing

### CODE REVIEW

**Comment by xinglong717** [comment]
I want to see the working sample.

**Comment by walec51** [comment]
this library provides a unified API for all exchanges so I don't know why would you expect a sample for ever exchange

**Comment by xinglong717** [comment]
I'm doing one crypto currency project. I'm first in XChange. I do'nt know to use it. So I made some code for bl3p using ccxt python library. It's the reason that I want sample.

**Comment by AmazingDreams** [comment]
You can check out the test directory of the bl3p implementation, alongside the existing samples provided by XChange. There is little to no difference between different exchanges with XChange

xinglong717 <notifications@github.com> schreef op 22 september 2019 16:42:26 CEST:

**Pull request merged**
