### PR TITLE
[Streaming] issue #3542: Remove unused error field and ignore null fields when serializing

### PR DESCRIPTION
**Pull request by wvos**
removing null fields from json serialized subscription message

### CODE REVIEW

**Comment by mdvx** [comment]
Was the error field recently removed by Kraken?  I was added because it was returned by the REST/Sockets calls

**Comment by wvos** [comment]
there is no error field on the request messages - see: https://docs.kraken.com/websockets/#message-subscribe.  For an error response message https://docs.kraken.com/websockets/#errortypes you have an event 'error' and errorMessage with details which is being dealt with correctly so no changes there.  The change is fix the incorrect formatting of the json request msg. I validated this through the test classes you already have and by using this api in a project

**Comment by mdvx** [comment]
ok, fair enough.  I now suspect it was in a beta API, and has since been cleaned up.  I checked 1.0.1 and 1.1.0

**Comment by wvos** [comment]
@mdvx even though I think the changes I made is relevant, it looks like the code is working in the develop branch.  When I started this I pulled in the snapshot compiled version from https://oss.sonatype.org/content/groups/public/org/knowm/xchange/ which gave me the errors I mentioned.  The changes in this PR ensures the null fields doesn't get serialized although it seems to already happen in the latest version

**Pull request merged**
