### PR TITLE
[Coindeal,Itbit,Quoine]

### PR DESCRIPTION
**Pull request by makarid**
Adding Coindeal exchange.
Adding Itbit PostOnlyFlag and postOnly functionality
Making Quoine wallets name field, human readable in order to choose easily between wallets.

### CODE REVIEW

**Comment by timmolter** [comment]
could you improve error handling to follow best practices stated at:
https://github.com/knowm/XChange/wiki/New-Implementation-Best-Practices#step-7

take a look at the bittrex module for an example:
https://github.com/knowm/XChange/tree/develop/xchange-bittrex

**Comment by makarid** [comment]
I have fixed the Error Handling on CoindealExchange as you stated. I haven't done any ErrorAdapter because there isn't any standard json error returning format on Coindeal Exchange API.I am waiting for your response.Thanks

**Comment by walec51** [comment]
I confirm that CoinDeals error response format is wildly inconsistent - its like totally different in various situations.

However we can still try to handle some situations in some loose way. Please take a look at my PR that does this: https://github.com/knowm/XChange/pull/3140

^ can we merge this first so you could adjust your code?

My PR also shows where adapting CoindealException to more generic xchange-core exceptions should be done. Doing it in *Raw methods is wrong.

**Comment by walec51** [comment]
PS. Did you build the code from this PR using maven before pushing?
Maven fixes formatting automatically in this project but your code fails to follow some conventions in many places.

**Comment by makarid** [comment]
@walec51 thanks for your response. Yes i built it from Maven. The thing is that i was testing the google format plugin in intellij and i know if this plugin changed something in the format. I still don't have the knowledge for formatting.

**Comment by makarid** [comment]
I have fixed some minor issues and now it is ready to merged. I have update my fork in order to be up to date with the main branch. Waiting for your response.Thanks

**Comment by walec51** [comment]
to fix the formatting just do `mvn clean install' on the modules you edited and push the resulting changes via git

if you have an IDE plugin that automatically formats files then turn it off or make it match the format enforced by the maven plugin: https://github.com/coveooss/fmt-maven-plugin

besides the inconsistent formatting everything looks ok to me

**Comment by makarid** [comment]
Thanks a lot for your help. I will do it very soon.

**Comment by makarid** [comment]
> to fix the formatting just do `mvn clean install' on the modules you edited and push the resulting changes via git
> 
> if you have an IDE plugin that automatically formats files then turn it off or make it match the format enforced by the maven plugin: https://github.com/coveooss/fmt-maven-plugin
> 
> besides the inconsistent formatting everything looks ok to me

@walec51 i just fixed the format inconsistencies as you instruct me.

**Pull request merged**
