### PR TITLE
Add missing currencies + rate limits + allow creation of orders from JSON

### PR DESCRIPTION
**Pull request by sebastienkoch**
Add missing currencies for some exchanges
Add rate limits for some exchanges
Allow creation of orders from JSON

### CODE REVIEW

**Comment by timmolter** [comment]
I don't want to make the DTOs mutable, hence the `final` keywords need to stay. Also, I don't want to allow for annotations like `@JsonIgnore`. These topics have been discussed before, not that I expect you to have seen them, and I'll refrain from writing out all the reasons here for now.

**Comment by sebastienkoch** [comment]
It would be pratical to have DTOs mutable in order to be able to store them in JSON format, and then deserialise them when necessary (for exemple for testing purpose).

If you don't want to approve this modification, could you please at least commit the others?

**Comment by timmolter** [comment]
You can serialize an immutable object to JSON. That should be no issue. 

No, I am not able to select out the changes that we'd like to keep. Can you do it from your end?

**Comment by walec51** [comment]
@sebastienkoch will you be working on this PR?
if not then will have to close it

**Pull request closed without merging**
