### PR TITLE
[core] BigDecimalUtils with rounding to step size

### PR DESCRIPTION
**Pull request by walec51**
functionality suggested by @makarid  in https://github.com/knowm/XChange/pull/3201

### CODE REVIEW

**Comment by makarid** [comment]
Thanks @walec51

**Comment by walec51** [comment]
if this is ok with you then I'll merge

I'll also use it in my OrderValuesAdjuster for order amounts (I plan to contribute it next week)

**Comment by makarid** [comment]
Yeah it is ok. I will add it to Bitmex placeOrder and Itbit placeOrder method also when you merge

**Comment by walec51** [comment]
@makarid I don't think that rounding the orders limit price / amount in placeOrder is a good idea.

You should handle this when building the order by either:
a) validating the input data in accordance to CurrencyPairMetaData
b) adjust the values then constructing an order
I'll submit a PR with a helper class for that today.

**Comment by walec51** [comment]
@makarid this helper will solve your problem at the proper stage - while building the order, not when placing it: https://github.com/knowm/XChange/pull/3204

**Pull request merged**
