### PR TITLE
General repo build errors

### PR DESCRIPTION
**Pull request by nibarulabs**
These were some minor errors that I came across when trying to install the entire repo locally via mvn install.

There is one issue I cannot figure out however; xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProExchange.java line 134 has the NoArgsConstructor annotation and maven complains about it. I commented it out - temporarily - to get everything to build.

My machine config is as follows:

```
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T11:49:05-08:00)
Maven home: /home/nibarulabs/projects/apache-maven-3.5.3
Java version: 1.8.0_282, vendor: AdoptOpenJDK
Java home: /home/nibarulabs/projects/jdk8u282-b08/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.12.16-1-manjaro", arch: "amd64", family: "unix"
```

I'm using intelliJ : 

```
IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.12.16-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 24
Registry: eslint.additional.file.extensions=svelte
Non-Bundled Plugins: Rider UI Theme Pack (0.9.3), com.intellij.plugins.watcher (211.6693.44), google-java-format (1.9.0.1), id.mustofa.breeze-dark (0.2), dev.blachut.svelte.lang (0.20.0), org.jetbrains.kotlin (211-1.5.21-release-317-IJ7442.40)
Kotlin: 211-1.5.21-release-317-IJ7442.40
Current Desktop: KDE
```

I have spent hours trying to fig out why maven does not like that annotation. Any thoughts on how to fix this would be appreciated.

### CODE REVIEW

**Comment by nibarulabs** [comment]
@earce Looking at this again, I can create a new PR if wanted. I'm not sure what happened with the CryptoFacilitiesDigest file as I forked from develop a few days ago... I just reverted the file and re-pushed.

**Comment by walec51** [comment]
we build this project regularly as is

which version of the JDK are you using?

please paste the output you got from maven when building develop

**Comment by nibarulabs** [comment]
Hi @walec51 

My jdk config from above is:

```
Java version: 1.8.0_282, vendor: AdoptOpenJDK
Java home: /home/nibarulabs/projects/jdk8u282-b08/jre
```

I get the errors when i run an ```mvn install``` so I can setup the jars in my local .m2 maven. I will be at my desk in a bit and will paste the errors. Thanks.

**Comment by nibarulabs** [comment]
Here are the errors from a brand new fresh check out:

```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.806 s <<< FAILURE! - in org.knowm.xchange.bittrex.service.TradeServiceTest
[ERROR] org.knowm.xchange.bittrex.service.TradeServiceTest.cancelOrderTest  Time elapsed: 0.027 s  <<< ERROR!
java.lang.IllegalArgumentException: argument "source" is null
        at org.knowm.xchange.bittrex.service.TradeServiceTest.cancelOrderTest(TradeServiceTest.java:70)
```

The above is because of the PLACEDORDER_FILE_NAME constant not matching the testing resource file.

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/nibarulabs/projects/xchange-temp/XChange/xchange-coinbasepro/src/main/java/org/knowm/xchange/coinbasepro/CoinbaseProExchange.java:[134,4] cannot find symbol
  symbol:   class NoArgsConstructor
  location: class org.knowm.xchange.coinbasepro.CoinbaseProExchange

```

The above is because of the NoArgsConstructor Lombok annotation.


Some existing Kucoin errors:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/nibarulabs/projects/xchange-temp/XChange/xchange-examples/src/main/java/org/knowm/xchange/examples/kucoin/trade/KucoinTradeRawDemo.java:[228,52] method getKucoinFills in class org.knowm.xchange.kucoin.KucoinTradeServiceRaw cannot be applied to given types;
  required: java.lang.String,java.lang.String,int,int,java.lang.Long,java.lang.Long
  found: <nulltype>,int,int,<nulltype>,<nulltype>
  reason: actual and formal argument lists differ in length
[ERROR] /home/nibarulabs/projects/xchange-temp/XChange/xchange-examples/src/main/java/org/knowm/xchange/examples/kucoin/trade/KucoinTradeRawDemo.java:[230,43] method getKucoinFills in class org.knowm.xchange.kucoin.KucoinTradeServiceRaw cannot be applied to given types;
  required: java.lang.String,java.lang.String,int,int,java.lang.Long,java.lang.Long
  found: java.lang.String,int,int,<nulltype>,<nulltype>
  reason: actual and formal argument lists differ in length
[INFO] 2 errors 
```

FTX error:

```
[INFO] Running org.knowm.xchange.ftx.FtxAdapterTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.194 s - in org.knowm.xchange.ftx.FtxAdapterTest
[INFO] Running org.knowm.xchange.ftx.dto.account.AccountDtosTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.017 s <<< FAILURE! - in org.knowm.xchange.ftx.dto.account.AccountDtosTest
[ERROR] org.knowm.xchange.ftx.dto.account.AccountDtosTest.accountDtoUnmarshall  Time elapsed: 0.015 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<["sell"]> but was:<[sell]>
        at org.knowm.xchange.ftx.dto.account.AccountDtosTest.accountDtoUnmarshall(AccountDtosTest.java:32)
```

Kraken:

```
[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.014 s <<< FAILURE! - in info.bitrich.xchangestream.kraken.KrakenStreamingServiceTest
[ERROR] info.bitrich.xchangestream.kraken.KrakenStreamingServiceTest.testParseOrderbookSizeReturnsDefaultWhenNoArgsGiven  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError: expected:<25> but was:<null>
        at info.bitrich.xchangestream.kraken.KrakenStreamingServiceTest.testParseOrderbookSizeReturnsDefaultWhenNoArgsGiven(KrakenStreamingServiceTest.java:21)

[ERROR] info.bitrich.xchangestream.kraken.KrakenStreamingServiceTest.testParseOrderbookSizeReturnsDefaultOnInvalidValue  Time elapsed: 0.006 s  <<< FAILURE!
java.lang.AssertionError: expected:<null> but was:<25>
        at info.bitrich.xchangestream.kraken.KrakenStreamingServiceTest.testParseOrderbookSizeReturnsDefaultOnInvalidValue(KrakenStreamingServiceTest.java:11)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   KrakenStreamingServiceTest.testParseOrderbookSizeReturnsDefaultOnInvalidValue:11 expected:<null> but was:<25>
[ERROR]   KrakenStreamingServiceTest.testParseOrderbookSizeReturnsDefaultWhenNoArgsGiven:21 expected:<25> but was:<null>
[INFO] 
[ERROR] Tests run: 11, Failures: 2, Errors: 0, Skipped: 0
```

Most of these are simple easy fixes. Let me know next steps.

**Comment by timmolter** [comment]
it looks like travis-ci stopped supporting open source projects so XChange hasn't been automatically tested in a while. I need to convert to Github actions...

**Comment by timmolter** [comment]
thanks for fixing these

**Comment by nibarulabs** [comment]
@timmolter Gald I can help, you guys have done a lot of great work.

**Pull request merged**
