### PR TITLE
[core] Order book synchronized

### PR DESCRIPTION
**Pull request by rizer1980**
Added OrderBook synchronization through the StampedLock mechanism, which is much faster and more flexible than usual Synhcronzed.
That gives us the opportunity to receive a full copy of the orderbook without a chance to get an Concurrent exception.

### CODE REVIEW

**Comment by rizer1980** [comment]
bump

**Comment by rizer1980** [comment]
ping

**Comment by timmolter** [comment]
It's hard for me to tell if this PR works as designed in addition to not breaking things for someone relying on this.

**Comment by rizer1980** [comment]
added concurrency tests.
1. New way, in use StampedLock
2. Old way, Stampdelock wrapped in Synchonized

**Pull request closed without merging**
