### PR TITLE
[Bibox] Fixed get balances

### PR DESCRIPTION
**Pull request by cymp**

### CODE REVIEW

**Comment by cymp** [comment]
@timmolter Please have a look at 1a654ba. Any idea why the compilation fails and forces me to do that? I would expect the lombok dependency to be resolved with the dependency to core...

**Comment by cymp** [comment]
It's in the root pom though, what should we do?

**Comment by timmolter** [comment]
actually, they way you did it is correct. It's only defined in the parent pom, and only the modules that depend on it should explicitly define it.

**Comment by cymp** [comment]
ok so I think you can merge :)

**Pull request merged**
