### PR TITLE
[Binance] Adding support for Binance futures

### PR DESCRIPTION
**Pull request by makarid**

### CODE REVIEW

**Comment by makarid** [comment]
Please do not merge it yet, i have to add future streaming support + futureExchangeMetaData. You can check it until i send the last updates. Thanks

**Comment by makarid** [comment]
My thinking on this implementation is to have one exchange BinanceExchange in which we can call FuturesApi endpoint based on the Instrument type that we send. If we send a CurrencyPair instance, we will get a spot API response and if we send a FutureContract instance we will get a future API response. The same will be try for COIN-MARGINED API. We can send for example a FutureContract("BTC/USDT/USDT") and it will call the Futures API, but if we send a FutureContract("BTC/USDT/COIN") it will use the coinMargined API. What do you think about this implementation? Thank you

**Comment by makarid** [comment]
It is better to merge #4618 before merging this.

**Comment by m1dnightc0der** [comment]
@makarid is this ready to merge, once https://github.com/knowm/XChange/pull/4618 is merged?

**Comment by makarid** [comment]
Mostly yes

Στις Δευ 28 Νοε 2022 στις 4:22 μ.μ., ο/η m1dnightc0der <
***@***.***> έγραψε:

**Comment by timmolter** [comment]
4618 is merged, please fix merge conflicts here

**Comment by makarid** [comment]
Thank you @Tim Molter ***@***.***>

Στις Τρί 29 Νοε 2022 στις 12:01 π.μ., ο/η Tim Molter <
***@***.***> έγραψε:

**Comment by m1dnightc0der** [comment]
@timmolter merge me baby one more time!

**Comment by makarid** [comment]
The way that i have implement the Future markets is the following.

For xchange-binance module the user just changes the type of the Instrument from CurrencyPair to FutureContract and the API will call the Future markets. So with one BinanceExchange instance you can call both spot and future markets.
For xchange-stream-binance i have created a new BinanceStreamingFuture class in order to call the futures API.

**Comment by m1dnightc0der** [comment]
@timmolter you ok to merge this if you get a sec

**Comment by makarid** [comment]
Please do not merge yet, it has issues with FutureStreamingExchange. I need to fix it first

**Comment by makarid** [comment]
Hello, i think it is ready now, please check

**Comment by timmolter** [comment]
ready to merge once the breakages are fixed

**Comment by makarid** [comment]
it is ready @timmolter you can merge it. Thanks

**Comment by kovalu** [comment]
Hi @makarid, @timmolter - these changes caused that xchange broke for some of Binance users, please see created issues:
https://github.com/knowm/XChange/issues/4661

**Pull request merged**
