### PR TITLE
Changes to itBit API

### PR DESCRIPTION
**Pull request by chrisrico**
As of 2019-02-25 they now support 8 decimal places of precision
On 2019-02-28 they will support market orders

Both of these changes are documented in their [staging API documentation](https://staging-api.itbit.com/docs).

### CODE REVIEW

**Comment by chrisrico** [comment]
Hmm, this isn't going to work. Their API is weird and needs a fiat amount in `funds` when placing a BUY market order, but a crypto amount in `amount` when placing a SELL. I don't think that will work with the MarketOrder API unless we calculate the fiat amount based on the order book, which seems highly sub-optimal.

**Comment by timmolter** [comment]
I'm not really sure. You'll have to do some trial and error testing.

**Comment by chrisrico** [comment]
I don't think I explained my question very well. What I mean is this:

itBit expects to receive a fiat amount when issuing a buy order, and a crypto amount when issuing a sell order. Is it safe *from an API perspective*, to expect the same value (`MarketOrder.getOriginalAmount()`) to refer to either a fiat amount or a crypto amount depending on the `MarketOrder.getType()`?

**Comment by timmolter** [comment]
From the high level XChange API, it should behave like all the other modules so that there are no surprises. If you need to do some conversions at the *Raw level before sending the requests off to itBit then that's how it should be done.

**Comment by walec51** [comment]
@chrisrico will you be working on this PR?
if not then will have to close it

**Pull request closed without merging**
