### PR TITLE
[quadrigacx] added withdrawal support for additional currencies: BCH, BTG, LTC

### PR DESCRIPTION
**Pull request by andre77**
due to the quadriga API design, one needs to add extra method for every currency, unfortunatelly...

### CODE REVIEW

**Comment by walec51** [comment]
use PathParam and implement come `currency to api name` mapping instead of adding a method for each crypto

**Comment by andre77** [comment]
@walec51 thanks for your comment. yes it could be an option
for now it was faster for me to keep the structure of methods 1:1
if quadriga adds 10 more currencies with 2x10 more methods, one should use your approach

**Comment by walec51** [comment]
to me this is just lazy copy-paste style coding and a bad practice that will be followed in the code
please improve the implementation, the point of code review is not to accept anything that works

**Comment by andre77** [comment]
@walec51 thanks for your comment.
i'm fine with the current implementation, it works und the way to provide methods in the interface 1:1 mapped to those from the API description is not the worst option, even though i do not like the c&p style. its not me, who copy&pasted the methods, its the devs by quadriga in this particular case.
feel free to improve it though and implement your suggestion

**Pull request merged**
