### PR TITLE
Removed Abucoins exchange which is no longer operating

### PR DESCRIPTION
**Pull request by milczarekIT**
Removed Abucoins exchange which is no longer operating: https://abucoins.com/en

### CODE REVIEW

**Comment by walec51** [comment]
isn't their API still available to download old users trades?

**Comment by milczarekIT** [comment]
Hi Adam,
I am not sure, because I do not have account here and I am not able to open it, because this exchange is dead. 'Register' button is still available, but it causes following error: "Due to company liqiduation process registrations are punt on hold."

(Public) API to download historical trades or order books does not exist.

**Comment by makarid** [comment]
I believe it is better to delete it. The exchange had ultra low volume even when it operated so not much damage will be done if we delete it.

**Comment by timmolter** [comment]
thanks!

**Pull request merged**
