### PR TITLE
[kucoin] funding methods like deposit and withdrawal

### PR DESCRIPTION
**Pull request by andre77**

### CODE REVIEW

**Comment by andre77** [comment]
@timmolter 
btw, have you seen the [lombok](https://projectlombok.org/) dependency in this module?
it was not added by me, but it's a very nice library, i simply love it
may be you can consider to add it on the core level

**Comment by timmolter** [comment]
lombok is configured at the core level. :)

**Comment by andre77** [comment]
@timmolter 
you commented here, but did not merge yet
why not? :-)

**Comment by cymp** [comment]
@andre77 maybe because the build failed.

**Comment by andre77** [comment]
@timmolter 

> [ERROR] Failed to execute goal on project xchange-bittrex: Could not resolve dependencies for project org.knowm.xchange:xchange-bittrex:jar:4.3.19-SNAPSHOT: Failed to collect dependencies at com.github.tomakehurst:wiremock:jar:2.23.2 -> org.eclipse.jetty:jetty-server:jar:9.2.26.v20180806: Failed to read artifact descriptor for org.eclipse.jetty:jetty-server:jar:9.2.26.v20180806: Could not transfer artifact org.eclipse.jetty:jetty-server:pom:9.2.26.v20180806 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]

i do not think, the error is related to my changes. can i retrigger the build some how without pushing any changes?

**Comment by timmolter** [comment]
i retriggered it on travisci.org. I'm not sure you have permissions to do that or not.

**Pull request merged**
