### PR TITLE
[Kraken-Streaming] fixing invalid session issues 

### PR DESCRIPTION
**Pull request by earce**
From an email I exchanged with Kraken support:

> Thank you for contacting us regarding the Kraken WebSocket API. In theory WebSocket authentication tokens can last indefinitely, but in reality they do sometimes expire causing an invalid session error. As an example, during a recent WebSocket API upgrade, many authentication tokens became invalid (for no apparent reason to the token owners), causing unexpected invalid session errors upon reconnecting/resubscribing after the upgrade. The solution to the invalid session error is simply to request a new authentication token via the REST API GetWebSocketsToken endpoint, and then use the new token for all new connections/subscriptions.

Based on this a few points come up that I attempt to address in this review:

1. In `KrakenStreamingTradeService.java` `subscribeChannel(channelName, renewToken().getToken())` is called with a token upon subscription so the instance of the token called here is reused for the duration of this process run (this sounds reasonable given that once a token is used to subscribe to a private feed a token will remain valid as long as a subscription remains active) [Kraken Documentation](https://support.kraken.com/hc/en-us/articles/360034664311-How-to-subscribe-to-the-Kraken-WebSocket-private-feeds). I see the code has `renewToken()` logic but given the fact that the token instance is passed directly into the subscription I am under the impression that this is never called during reconnects.

2. The scenario where the token becomes invalid due to something on their side and given our logic for token renewal we attempt to subscribe with a bad token before we our token lifespan has us consider the token invalid. This will cause a Session Invalid on our end and we won't attempt reconnect, rendering the websocket channel dead.

Edit:

3. I added an check for session invalid message coming back from Kraken which would indicate despite our efforts we still sent an invalid token, which would protect against the extremely unlikely situation where between us requesting a token and the submission the token became invalid. This removes all race conditions from our code.

Addresses what I investigated following https://github.com/knowm/XChange/issues/3683

### CODE REVIEW

**Comment by earce** [comment]
@mdvx 
@badgerwithagun

**Comment by earce** [comment]
hi wanted to bump this back up, was hoping to get it looked at

**Comment by earce** [comment]
@timmolter how would would you feel about looking at this review?

**Comment by badgerwithagun** [comment]
I'll look at this today. Been busy with work, sorry for the delay.

**Review by badgerwithagun — APPROVED** [review]

**Comment by panieldark** [comment]
Nice job! @earce

**Pull request merged**
