### PR TITLE
[Binance] Added sandbox support 

### PR DESCRIPTION
**Pull request by mrmx**
Added sandbox support for Binance exchange/streaming via exchangeSpecification.setExchangeSpecificParametersItem("Use_Sandbox", true)

The Binance spot testnet is located at https://testnet.binance.vision

### CODE REVIEW

**Comment by vaseok10** [comment]
Hi!
Thanks for update!
When we create standard Binance connection we use getDefaultExchangeSpecification(), setApiKey and setSecretKey to insatiate.
Do we need some other settings beside setExchangeSpecificParametersItem when we are instantiating testnet? For now it's throwing 404

**Comment by earce** [comment]
Not sure, you will need to see if the api tells you more and make you upgrade to the latest build version

**Comment by vaseok10** [comment]
I think the problem is in signature creator(org.knowm.xchange.binance.service.BinanceHmacDigest#getQuery)
Binance requires signature in path, and here I see it get's filtered   .filter(e -> !BinanceAuthenticated.SIGNATURE.equals(e.getKey())) 

When initializing the bean he is making some calls to get some data, which are failing

**Comment by vaseok10** [comment]
```
updated to latest build, using this to instantiate and failing :(
        ExchangeSpecification exchangeSpecification = new BinanceExchange().getDefaultExchangeSpecification();
exchangeSpecification.setApiKey("XXX");
        exchangeSpecification.setSecretKey("XXX");
exchangeSpecification.setExchangeSpecificParametersItem("Use_Sandbox", true);
return ExchangeFactory.INSTANCE.createExchange(exchangeSpecification);

```

**Comment by mrmx** [comment]
That error 404 is because in the testnet there is no wapi/v3/assetDetail.html endpoint present when the remoteInit method is called (from createExchange). At the moment there is no workaround.

**Pull request merged**
