### PR TITLE
fix Hitbtc USDT balances

### PR DESCRIPTION
**Pull request by JBetser**
simply adds a mapping USD -> USDT in the hitbtc balance adapter

### CODE REVIEW

**Comment by walec51** [comment]
does this code mismatch only happen in wallet information?
other endpoint use USDT correctly?

**Comment by timmolter** [comment]
My gut tells me this will break things. Can someone who uses Hitbtc chime in?

If an exchange uses USDT as a counter currency, then just use the USDT Currency. If it uses USD, then use the USD Currency.

**Comment by fxmozart** [comment]
Hitbtc doesnt allow withdraw on usdt , so prices are skewed.



Olivier G.

**Comment by walec51** [comment]
in their UI everywhere I see USDT instead of USD

now how does this look in their API?
do they use USD code instead od USDT everywhere?
or is it just in the wallet endpoint as this PR suggests?

**Comment by fxmozart** [comment]
Its not buggy per say , they just dont allow users to withdraw in usdt for
a few months now .




Olivier Guiglionda


Mobile Phone : +33768461000

**Comment by JBetser** [comment]
this problem is unrelated to the fact USDT withdrawals are currently disabled.
you can still read the balances and trade USDT in hitbtc.

**Comment by walec51** [comment]
well then this is an extension of this problem https://github.com/knowm/XChange/issues/2394

and hacking it for one endpoints response object is not a solution - it would be introducing an inconsistency only

besides, they may already be applications that use this module with USD despite knowing that its actually USDT on this exchange

**Comment by walec51** [comment]
I'd suggest that for now you should solve the problem on your applications level and join the disquisition on how to solve https://github.com/knowm/XChange/issues/2394

**Pull request closed without merging**
