### PR TITLE
[Bitstamp streaming]: Implement getTicker

### PR DESCRIPTION
**Pull request by dazito**

### CODE REVIEW

**Comment by timmolter** [comment]
Please check the failing test!

**Comment by dazito** [comment]
> Please check the failing test!

I know, as I said on discord I will fix it soon. 
The unit test is failing because it is expecting a `NotAvailableFromExchangeException` to be thrown on the method I just implemented.

**Comment by dazito** [comment]
Regarding the PR, are you fine with the changes? I based my code on the Gemini Stream implementation because Bitstamp ticket channel does not provide us enough information for the Ticker object.

https://www.bitstamp.net/websocket/v2/

**Comment by timmolter** [comment]
yeah, looks good! Sorry, I missed that on Discord.

**Comment by dazito** [comment]
Fixed the unit test.

**Pull request merged**
