### PR TITLE
[Coincheck] Initial market data implementation

### PR DESCRIPTION
**Pull request by kennethjor**

### CODE REVIEW

**Comment by kennethjor** [comment]
This PR ended up containing a bunch of reformatting for files outside the scope. Let me know if you'd like me to revert these.

**Comment by earce** [comment]
Can you break this out into 2 PRs, one thats specifically for coincheck stuff and another which is the modifications to the non-coincheck stuff.

**Comment by kennethjor** [comment]
I have created https://github.com/knowm/XChange/pull/4432 and https://github.com/knowm/XChange/pull/4433. There are two more changed files in there unrelated to Coincheck, will pull those out later.

**Comment by kennethjor** [comment]
@earce Done :+1:

**Pull request merged**
